okc_blog:
    resource: "@OkcBlogBundle/Resources/config/routing.yml"
    prefix:   /

okc_user:
    resource: "@OkcUserBundle/Resources/config/routing.yml"
    prefix:   /

okc_site_site:
    resource: "@OkcSiteBundle/Resources/config/routing.yml"
    prefix:   /

_tns:
    resource: "@OkcTnsBundle/Resources/config/routing.yml"