parameters:
#    okc_site_site.example.class: Okc\Site\SiteBundle\Example

services:
#    okc_site_site.example:
#        class: %okc_site_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
