parameters:
#    okc_user.example.class: Okc\User\UserBundle\Example

services:
#    okc_user.example:
#        class: %okc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
