Okc\TnsBundle\Model\calculsChargesEntreprise:
    properties:
        caHt:
            - Type:
                type: numeric
                message: La valeur {{ value }} n'est pas un type {{ type }} valide.