parameters:
#    okc_blog.example.class: Okc\BlogBundle\Example

services:
#    okc_blog.example:
#        class: %okc_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
